name: Service Grapher Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile Jsonnet
        uses: alexdglover/jsonnet-render@v2
        with:
          file: graph.jsonnet
          output_file: graph.json

      - name: Upload Service Graph
        uses: actions/upload-artifact@v3
        with:
          name: graph
          path: graph.json
          retention-days: 5

  deploy:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Service Graph
        uses: actions/download-artifact@v3
        with:
          name: graph

      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
